### ISSUE TITLE
Home App says no response

### ISSUE THREAD

**Issue by hmook** [arnif/homebridge-sony-television#12]
Hi,

Last Monday I have updated to iOS12.2 hoping to finally use your Sony Bravia TV plugin. I've first installed the plugin and edited the config on my existing homebridge installation. After this all the homebridge devices were unable to reach and all saying No Response.

Today I've tried installing homebridge on a different raspberrypi and only installing the Bravia plugin. First it seems to work for just a couple of minutes after that my television is stating 'No Response' in the Apple HomeApp. Error logs on both devices didn't show something that was alarming to me. Only line that is showing some kinda error is the following:

`Plugin /homebridge/node_modules/homebridge-bravia-tv requires Node version of ^8.9.1 which does not satisfy the current Node version of v10.15.3. You may need to upgrade your installation of Node.`

Hope this helps in fixing the plugin and looking forward to use it.

**Comment by arnif** [comment]
according to that you are trying to start this plugin: https://github.com/SeydX/homebridge-bravia-tv#readme thats not the same as this.

**Comment by hmook** [comment]
You are right. Mixed up with tabs sorry for that.

**Comment by hmook** [comment]
Actuale I dubble checked I was not. I was on this NPM repo which I think is yours?

[https://www.npmjs.com/package/homebridge-sony-television](https://www.npmjs.com/package/homebridge-sony-television)

**Comment by arnif** [comment]
Yes thats mine, strange the logs show another plugin.

**Comment by hmook** [comment]
Yes there is another plugin that's the UX UI interface. I'm using Homebridge as a docker container.

Configuration UI plugin for Homebridge
