### ISSUE TITLE
TV shows always on / Inputs can not selected

### ISSUE THREAD

**Issue by ghost** [arnif/homebridge-sony-television#2]
Hello! 

Thanks for this fast build for HomeKit TV! 

I found two issues:
1. TV button as on when off 
2. Inputs can not selected via Inputs
![img_1956](https://user-images.githubusercontent.com/47074811/51798547-9d952b80-2214-11e9-8a05-bbb439fb4c25.png)
![img_1957](https://user-images.githubusercontent.com/47074811/51798548-9d952b80-2214-11e9-9c44-cb6003cd0009.png)
![img_1958](https://user-images.githubusercontent.com/47074811/51798549-9d952b80-2214-11e9-9e64-9a3ddd560dce.png)

**Comment by arnif** [comment]
Hi, thanks for trying this out :)

1. I'm still working on that. Currently its just always set to true.

2. Did you see the inputs before you renamed them ? This could be related to the cache folder. (in the `~/.homebridge` directory). Could also be related to the language, I've only tested this on my device which is set to english.

**Comment by arnif** [comment]
1. is fixed in latest version

This is how my Input drawer looks like:
![img_0478a03ebaa9-1](https://user-images.githubusercontent.com/1312916/51799428-c8817e80-2218-11e9-9839-7dad7ba0843a.jpeg)

**Comment by Silvan-M** [comment]
Hello, I haven't renamed the inputs yet and can't see them.
After renaming they're still invisible like the picture in the first post.
TV button works as expected.

Thanks a lot for that build!

**Comment by ghost** [comment]
Just Update to Build 0.0.3 and all Works!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Silvan-M** [comment]
I'm already on Build 0.0.3.

**Comment by ghost** [comment]
My Inputs work also After I renamed them

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arnif** [comment]
Fantastic to hear @idominik94 :) 

@xBotRaid try force closing the app and open it again. Also restart homebrige.

**Comment by Silvan-M** [comment]
Ok, I'm trying...

**Comment by Silvan-M** [comment]
Having problems with my systemctl...

**Comment by arnif** [comment]
ok thats sounds like a homebridge issue.

**Comment by Silvan-M** [comment]
Ok, solved the homebridge issue, the old plugin was not properly uninstalled.

Now to the problem again: 
1. Tried forceclosing Home App
2. Rebooted Homebridge couple of times and forceclosing
3. Reinstalled plugin and resetup config file (again renaming inputs)
-> Still no inputs selectable

Renamed inputs:
![img_7284](https://user-images.githubusercontent.com/39488325/51805125-f93dd400-2269-11e9-82fb-106abff6d18f.png)

Home App after restart and force closing (iOS):
![img_7283](https://user-images.githubusercontent.com/39488325/51805133-0fe42b00-226a-11e9-88bd-27b0aa1cbb01.png)

(Experimental) Home App on the Mac after force close and reboot:
<img width="787" alt="screenshot 2019-01-27 at 19 25 23" src="https://user-images.githubusercontent.com/39488325/51805138-28ecdc00-226a-11e9-8caa-e560daaceac4.png">

Thanks again for creating this awesome plugin!

**Comment by arnif** [comment]
what if you run up another instance of homebridge ? and only have this plugin setup as an accessory and nothing else ?

**Comment by Silvan-M** [comment]
Same issue after trying, renaming and restarting.

**Comment by janthony6** [comment]
working great so far.  i have all my inputs on hdmi 3 arc so it would be nice to somehow use the tv to change to different devices.  also control volume/mute.  i tried adding "volumeControl": "switch", to my config but it didn't do anything.

**Comment by arnif** [comment]
Volume is not a switch its part of the TV widget (outside the Home app).
Same functionality as using iPhone/iPad as Apple TV remote now you get to select the television also and use the volume up/down to adjust volume.

**Comment by arnif** [comment]
@xBotRaid that's strange. I'm out of ideas, maybe ask around in the homebridge project ?

**Comment by Silvan-M** [comment]
I'll try! Maybe also a HomeKit bug, don't forget it's beta 1...

Thanks anyways!

**Comment by janthony6** [comment]
Okay I see it in control center.  I don’t see anywhere to adjust volume but I can control the menu with it now.  

Are there any settings to input to select a different hdmi 3 source.  Like from the menu on my tv I can select PlayStation, Apple TV, directv, etc and all are hdmi3.

**Comment by arnif** [comment]
the volume isn't adjusted with any slider, just the volume up/down button on the phone.

If the TV is showing the inputs as then it should probably be possible. Do you se the devices plugged into hdmi3 if you run this in terminal:

```
curl -H "Content-Type: application/json" \
  -H "X-Auth-PSK: YOUR_PSK_KEY" \
  -X POST \
  -d '{"id": 20, "method": "getCurrentExternalInputsStatus", "version": "1.0", "params": [""]}' \
  http://TV_IP_ADDRESS/sony/avContent
```

if so what is the uri value for those inputs ?

**Comment by Silvan-M** [comment]
I get following:

`{"result":[[{"uri":"extInput:cec?type=freeuse&port=3&logicalAddr=5","title":"Receiver","connection":true,"label":"","icon":"meta:freeuse"},{"uri":"extInput:hdmi?port=1","title":"HDMI 1","connection":false,"label":"PS4 Pro","icon":"meta:hdmi"},{"uri":"extInput:hdmi?port=2","title":"HDMI 2","connection":true,"label":"AppleTV","icon":"meta:hdmi"},{"uri":"extInput:hdmi?port=3","title":"HDMI 3\/ARC","connection":false,"label":"Blu-ray","icon":"meta:hdmi"},{"uri":"extInput:hdmi?port=4","title":"HDMI 4","connection":false,"label":"","icon":"meta:hdmi"},{"uri":"extInput:composite?port=1","title":"AV","connection":false,"label":"","icon":"meta:composite"},{"uri":"extInput:widi?port=1","title":"Bildschirm spiegeln","connection":true,"label":"","icon":"meta:wifidisplay"}]],"id":20}`

Seems to work just fine, probably a HomeKit issue since we're in beta 1.

I have just experienced a bug, that the input names would change back to default.
(for example "HDMI 1" manually defined: "HDMI 1"->"hdmi1")

**Comment by Silvan-M** [comment]
In all of the sudden, it works now! 😀👍🏻

Only thing: If you switch Input manually it will not change in the Home App

**Comment by arnif** [comment]
Yeah that's an improvement I need to make. Or maybe not, why change manually when you can use the phone :p

**Comment by Sammy990** [comment]
@xBotRaid what you did mate so you got the inputs showing?
Tried everything mentioned here, but still not getting the inputs selectable.
However they're shown in the settings of the TV like HDMI 1, HDMI 2, HDMI 3, HDMI 4, Netflix

Any help would be highly appreciated

**Comment by Silvan-M** [comment]
I literally just waited, at one point it worked. I don't really have any suggestions, sry...
I'd just try playing around reinstalling waiting. It's like gambling... 😂
I'd wait for next beta.

**Comment by Sammy990** [comment]
Figured out. Inputs started to work once I physically returned home and the phone joined my home wifi.
