### ISSUE TITLE
TV is showing as incompatible

### ISSUE THREAD

**Issue by luizjunior** [arnif/homebridge-sony-television#3]
I've following the configuration steps, but my TV is showing as incompatible on Home app .

**Comment by arnif** [comment]
do you have ios 12.2 ?

**Comment by luizjunior** [comment]
> do you have ios 12.2 ?

I'm transfering 12.1.3 update right now.

The 12.2 is in beta?

**Comment by arnif** [comment]
yes you need 12.2 which is in developer beta.

**Comment by luizjunior** [comment]
> yes you need 12.2 which is in developer beta.

ok I'll install this.
