### ISSUE TITLE
Home app says no response on the tv

### ISSUE THREAD

**Issue by ronvandeven** [arnif/homebridge-sony-television#8]
Initially homebridge would crash, now with the latest build of the plugin it stays stable, but the tv shows no response in the iOS home app. Checked ip adress, preshared key.

**Comment by arnif** [comment]
what do the logs say ?

**Comment by ronvandeven** [comment]
I'm quite new at this, where can I find the log, or how do I trigger a log export from the terminal?

**Comment by arnif** [comment]
Here is good information on how to view the logs in homebridge: https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#examine-logs-for-errors
