### ISSUE TITLE
Missing Inputs / DVB:T/C/S

### ISSUE THREAD

**Issue by ezadoo** [arnif/homebridge-sony-television#9]
Is there a way to add the DVB:T / DVB:S / DVB:C as selectable input. 
In my case, when DVB:S is selected, it's showing as HDMI 1, so I can't switch back from YouTube to Live-TV.

**Comment by arnif** [comment]
current implementation only has 4 hdmi and netflix button. Future versions might include dynamic detection of inputs and/or more customised input selection.

**Comment by Silvan-M** [comment]
I'd be nice to have a YouTube-App integration.
